export default {
  btnFilm: document.querySelector('.btn-hero1'),
  form: document.querySelector('.hero1-search'),
  noSearchName: document.querySelector('.js-hero1-no-search-name'),

  inputFilm: document.querySelector('#hero1-inputr'),
  ulGallery: document.querySelector('.js-gallery'),
  ulLibrary: document.querySelector('.js-library'),
  modalInfo: document.querySelector('.js-modal-info'),
  backdrop: document.querySelector('.backdrop'),
  closeModalBtn: document.querySelector('[data-action="close"]'),
  homeNav: document.querySelector('[data-home-page]'),
  libNav: document.querySelector('[data-lib-page]'),
  heroHome: document.querySelector('.hero1'),
  heroLib: document.querySelector('.hero'),
  watchedBtn: document.querySelector('[data-btn-watched]'),
  queueBtn: document.querySelector('[data-btn-queue]'),
  paginationList: document.querySelector('.pagination-list'),
  paginationMobileList: document.querySelector('.pagination-mobile-list'),
  paginationWrapper: document.querySelector('.pagination-wrapper'),
  btn18: document.querySelector('.btn18'),
  div: document.querySelector('.in-active'),
  modal18: document.querySelector('.modal18'),
};
