export default {
  btnFilm: document.querySelector(".btn-hero1"),
  inputFilm: document.querySelector("#hero1-inputr"),
  ulGallery: document.querySelector(".js-gallery"),
  ulLibrary: document.querySelector(".js-library"),
  modalInfo: document.querySelector(".js-modal-info"),
  backdrop: document.querySelector(".backdrop"),
  closeModalBtn: document.querySelector('[data-action="close"]'),
  homeNav: document.querySelector("[data-home-page]"),
  libNav: document.querySelector("[data-lib-page]"),
  heroHome: document.querySelector(".hero1"),
  heroLib: document.querySelector(".hero"),
  watchedBtn: document.querySelector("[data-watched]"),
  queueBtn: document.querySelector("[data-queue]"),
};
